### ISSUE TITLE
рефакторинг sqlalchemy кода

### ISSUE THREAD

**Issue by edloginova** [evkonovalov/textgericht#12]
Сейчас много дублирующегося кода в создании таблиц и обращении к ним.

**Comment by evkonovalov** [comment]
@edloginova  Тут тоже  https://github.com/evkonovalov/textgericht/commit/979c23b51b193a19d22ed2c8542e8c9eb0f985d5, это есть. Скажи елси нужно что то добавить.

**Comment by edloginova** [comment]
@evkonovalov А можно ли как-то сделать чтобы не пересоздавать объекты таблиц в update_db, analyse_db? Чтобы, например, убрать text_2_manipulation_methods = Table( на стр 33 flask/src/analyse_db.py
