### ISSUE TITLE
ускорить запрос к ChatGPT

### ISSUE THREAD

**Issue by edloginova** [evkonovalov/textgericht#5]

**Comment by evkonovalov** [comment]
Я попробую объеденить промты

**Comment by evkonovalov** [comment]
https://github.com/evkonovalov/textgericht/commit/87ba4b299cb93094b29c013a5a56988b67fbe4c5

**Comment by edloginova** [comment]
@evkonovalov это теперь всё один промпт, да? Мне кажется, по качеству не подходит нам, давай откатим и попробуем вместо этого запускать их параллельно (через тот жe multiprocessing?).

**Comment by evkonovalov** [comment]
Вот такой вариант https://github.com/evkonovalov/textgericht/commit/a20978d938c5ba8a3ed5598577b40fbb522506a2
Оказывается что модель Completion намного быстрее работает. У меня буквально за 10 секунд текст хорошо анализируется.
Если поменять назад на ChatCompletion то выигрыша по сравнению с прошлой версией особо никакого не нет. Один промт работает сильно дольше трех.

**Comment by evkonovalov** [comment]
Вот сравнение как они работают

###ChatCompletion (время работы - вечность (10 минут))

Результат анализа:
Приёмы манипуляции читателем
1. Манипуляция эмоциями: Автор текста использует эмоционально окрашенные слова и фразы, такие как "недовольный", "возмущенный отзыв", "шквал ругани", "наполненные ненавистью", чтобы вызвать негативные эмоции у читателя и создать негативное отношение к медику.

2. Манипуляция через авторитет: Автор упоминает профильную НКО, которая заявляет, что подаст на медика в суд, чтобы создать впечатление, что медик совершил что-то неправильное и нарушил закон. Это может вызвать у читателя симпатию к жалующемуся трансгендеру и негативное отношение к медику.

3. Манипуляция стереотипами: Автор описывает трансгендера как мужчину, который сбрил щетину и начал пить гормоны, чтобы стать "настоящей женщиной". Это создает стереотип о трансгендерах как людях, которые просто играют в противоположный пол, и может вызвать негативное отношение к ним.

4. Манипуляция через преувеличение: Автор утверждает, что медик не был готов "профессионально обслужить внутренние хотелки мужчины", что может быть преувеличением ситуации и создает впечатление, что медик совершил серьезное нарушение.

5. Манипуляция через сравнение: Автор сравнивает разбитую мечту трансгендера с мечтой Остапа Бендера, чтобы создать впечатление, что трансгендеру было нанесено большое эмоциональное и психологическое повреждение. Это может вызвать сочувствие у читателя и негативное отношение к медику.

Логические ошибки
1) В тексте нет подмены тезиса.
2) В тексте есть мнимая логическая связь. Автор связывает недовольство трансгендера и его партнера с последующими действиями НКО, предполагая, что именно недовольство стало причиной организации шквала ругани и заявления в суд. Однако, отсутствует прямая логическая связь между этими событиями, так как недовольство может быть причиной, но не обязательно приводить к таким последствиям.
3) В тексте нет ошибки выборки.
4) В тексте нет корреляции как причинно-следственной связи.

Язык ненависти
В данном тексте присутствуют высказывания, которые могут быть расценены как трансфобия и сексизм. В тексте содержится негативное отношение к трансгендерным людям, использование кавычек в отношении их самоидентификации и упоминание о "наполненных ненавистью в адрес трансгендера" высказываниях. Также в тексте присутствует пренебрежительное отношение к желаниям и самоопределению трансгендерных людей. Все эти элементы могут быть расценены как дискриминационные и стигматизирующие.

❌ Источники информации отсутствуют.

###Completion (Время работы - 10 секунд)

Результат анализа:
Приёмы манипуляции читателем


1. Использование эмоционально окрашенных слов и выражений (например, "недовольный", "возмущенный отзыв", "шквал ругани", "наполненные ненавистью", "хрустальная мечта", "разбитая мечта") - для создания негативного отношения к трансгендерам и поддержания интереса читателя.
2. Использование преувеличения (например, "шквал ругани", "наполненные ненавистью") - для усиления эмоциональной реакции читателя и создания впечатления о том, что ситуация является чрезвычайно серьезной.
3. Использование примеров из литературных произведений (например, "Остап Бендер") - для создания аналогии и усиления эмоциональной реакции читателя.
4. Использование техники "деления и правления" (например, упоминание о том, что трансгендер обратился не только в сетевое пространство, но и в НКО) - для создания впечатления о том, что мнение трансгендера поддерживается большим количеством людей и организаций.
5. Использование утверждений без доказательств (например, "вся вина медика заключалась в том, что он не был готов профессионально обслужить внутренние хотелки мужчины") - для создания впечатления о том, что медик виновен в конфликте и не выполнил свои профессиональные обязанности.
6. Использование техники "черно-белого мышления" (например, "настоящая женщина" против "мужчины") - для создания впечатления о том, что трансгендер не может быть настоящей женщиной и его желания и чувства не имеют права на существование.
7. Использование угрозы (например, "подаст на него в суд") - для создания впечатления о том, что медику грозит серьезное наказание за его высказывания.
8. Использование техники "перевернутого обвинения" (например, трансгендер обвиняет медика в том, что он не был готов обслужить его, в то время как сам трансгендер не уважает медика и его профессиональные знания) - для создания впечатления о том, что медик является виновным в конфликте, хотя на самом деле он стал жертвой манипуляций трансгендера.
9. Использование техники "перехода на личности" (например, упоминание о том, что трансгендер сбрил щетину и начал пить гормоны) - для создания впечатления о том, что трансгендер не является "настоящим" и его желания и чувства не имеют права на существование.
10. Использование техники "подмены понятий" (например, "внутренние хотелки мужчины" вместо "желание быть женщиной") - для создания впечатления о том, что желание трансгендера является неестественным и неправильным.

Логические ошибки


1) Подмена тезиса не обнаружена.
2) Мнимая логическая связь не обнаружена.
3) Ошибка выборки не обнаружена.
4) Корреляция как причинно-следственная связь не обнаружена.

Язык ненависти
В данном тексте присутствует дискриминационная лексика и высказывания в отношении трансгендерных людей. Термины "транс", "ненависть в адрес трансгендера", "настоящая женщина" используются с негативной коннотацией и могут оскорблять и унижать эту группу людей. Также в тексте присутствует стигматизирующее высказывание о том, что трансгендерный человек считает себя "настоящей женщиной" после сбривания щетины и приема гормонов. Это может быть оскорбительно и провоцировать ненависть к трансгендерным людям. Также можно отметить националистический подтекст в высказывании о "хрустальной мечте", который может быть расценен как расистский. В целом, данный текст содержит дискриминационную и стигматизирующую лексику и высказывания, которые могут провоцировать ненависть к определенной группе людей.

✅ Источники информации присутствуют.

**Comment by evkonovalov** [comment]
Да, он нашел какие то источники информации, но в целом то достойно
